// AUTOGENERATED FILE
// This file was generated from parser.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode,
} from "ohm-js";

export interface CardsActionDict<T> extends BaseActionDict<T> {
  Cards?: (this: NonterminalNode, arg0: IterationNode) => T;
  card?: (
    this: NonterminalNode,
    arg0: TerminalNode,
    arg1: NonterminalNode,
    arg2: TerminalNode,
    arg3: NonterminalNode,
    arg4: TerminalNode,
    arg5: NonterminalNode,
  ) => T;
  winningNumbers?: (this: NonterminalNode, arg0: IterationNode) => T;
  ownNumbers?: (this: NonterminalNode, arg0: IterationNode) => T;
  number?: (
    this: NonterminalNode,
    arg0: IterationNode,
    arg1: NonterminalNode,
  ) => T;
  digits?: (this: NonterminalNode, arg0: IterationNode) => T;
}

export interface CardsSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: CardsActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: CardsActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: CardsActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: CardsActionDict<T>): this;
}

export interface CardsGrammar extends Grammar {
  createSemantics(): CardsSemantics;
  extendSemantics(superSemantics: CardsSemantics): CardsSemantics;
}

declare const grammar: CardsGrammar;
export default grammar;
